import { z } from 'zod';
import type { Db } from '../store/db.ts';
import { getApplication, addEventForApplication, updateApplicationStatus } from '../store/application.ts';
import { getProfile } from '../store/profile.ts';
import type { Browser, FillField } from '../services/browser/types.ts';
import { writeResumeDocxToTemp, writeCoverLetterDocxToTemp } from '../services/browser/resumeFile.ts';
import type { SamplingClient } from '../sampling/client.ts';
import { sampleAnswerForFormField } from '../services/sampling/answerFormField.ts';
import { getJob } from '../store/job.ts';
import { getCompany } from '../store/company.ts';
import { getConfig } from '../store/appConfig.ts';
import { matchAnswer } from '../store/answerBank.ts';
import { resolveChoiceFields } from '../services/resolveChoices.ts';

export const applyApplicationInput = z.object({
  applicationId: z.string(),
  submit: z.boolean().optional()
});

export type ApplyApplicationResult = {
  applicationId: string;
  deepLink: string;
  resolvedUrl: string;
  title: string;
  /** PNG screenshot of the filled (but not submitted) form, base64-encoded. */
  screenshotPngBase64: string;
  /** Field kinds the browser successfully filled. */
  filled: string[];
  /** Field kinds the browser couldn't find a selector for. */
  skipped: string[];
  /** True if a submit button was clicked (v2.0+ opt-in via input.submit). False otherwise. */
  submitted: boolean;
  /** Path to the tailored resume DOCX written to /tmp. */
  resumeDocxPath: string;
  /** Path to the cover-letter DOCX. Undefined when the application has no cover letter. */
  coverLetterDocxPath?: string;
  /** Form-field names whose answers were generated by the LLM via sampling. */
  sampledFields: string[];
  /** ATS slug derived from the application's company. Null if the job/company isn't in the DB. */
  detectedAts: string | null;
  /** URL after submit click (post-navigation). Only set when submit succeeded. */
  postSubmitUrl?: string;
};

function asString(v: unknown): string | undefined {
  return typeof v === 'string' && v.length > 0 ? v : undefined;
}

export async function applyApplication(
  input: z.infer<typeof applyApplicationInput>,
  ctx: { db: Db; browser: Browser; sampling: SamplingClient }
): Promise<ApplyApplicationResult> {
  const app = getApplication(ctx.db, input.applicationId);
  if (!app) throw new Error(`unknown application: ${input.applicationId}`);

  const profile = getProfile(ctx.db) ?? {};
  const fields: FillField[] = [];

  const email = asString(profile.email);
  if (email) fields.push({ kind: 'email', value: email });

  const firstName = asString(profile.first_name);
  if (firstName) fields.push({ kind: 'first_name', value: firstName });

  const lastName = asString(profile.last_name);
  if (lastName) fields.push({ kind: 'last_name', value: lastName });

  const fullName = asString(profile.name) ?? asString(profile.full_name);
  if (fullName && !firstName && !lastName) {
    fields.push({ kind: 'full_name', value: fullName });
  }

  const phone = asString(profile.phone);
  if (phone) fields.push({ kind: 'phone', value: phone });

  const links = (profile.links ?? {}) as Record<string, unknown>;
  const linkedin = asString(profile.linkedin) ?? asString(links.linkedin);
  if (linkedin) fields.push({ kind: 'linkedin', value: linkedin });

  const website = asString(profile.website) ?? asString(links.website) ?? asString(links.portfolio);
  if (website) fields.push({ kind: 'website', value: website });

  const resumeDocxPath = await writeResumeDocxToTemp(app.tailoredResumeMd, app.id);
  fields.push({ kind: 'resume_file', path: resumeDocxPath });

  let coverLetterDocxPath: string | undefined;
  if (app.coverLetterMd && app.coverLetterMd.length > 0) {
    coverLetterDocxPath = await writeCoverLetterDocxToTemp(app.coverLetterMd, app.id);
    fields.push({ kind: 'cover_letter_file', path: coverLetterDocxPath });
    fields.push({ kind: 'cover_letter_text', value: app.coverLetterMd });
  }

  for (const [name, value] of Object.entries(app.answerPack)) {
    if (typeof value === 'string' && value.length > 0) {
      fields.push({ kind: 'text_by_name', name, value });
      // We don't have a label from the answer pack, but the apply pass will
      // also evaluate preview.formFields and may add a label-aware copy below.
    }
  }

  const sampledFields: string[] = [];
  const knownNames = new Set<string>();
  for (const f of fields) {
    if (f.kind === 'text_by_name') knownNames.add(f.name);
  }

  const job = getJob(ctx.db, app.jobId);
  const company = job ? getCompany(ctx.db, job.companyId) : null;
  const detectedAts = company ? company.ats : null;

  let preview: Awaited<ReturnType<Browser['preview']>> | null = null;
  try {
    preview = await ctx.browser.preview(app.deepLink);
  } catch {
    preview = null;
  }

  if (preview && preview.formFields.length > 0) {
    const jobContext = job
      ? `Applying to: ${job.title}${company ? ` at ${company.name}` : ''}`
      : 'a job application';
    // Bundle the tailored résumé (real work history) + cover letter so the
    // sampler has the candidate's actual employers/titles/dates, not just
    // motivational prose. The model was confusing target company with current
    // employer when only the cover letter was given.
    const resumeText = app.tailoredResumeMd ? `--- Applicant's résumé (true facts) ---\n${app.tailoredResumeMd.slice(0, 3000)}` : '';
    const coverText = (app.coverLetterMd && app.coverLetterMd.length > 0)
      ? `--- Applicant's cover letter ---\n${app.coverLetterMd.slice(0, 1200)}`
      : '';
    const applicantContext = [resumeText, coverText].filter(Boolean).join('\n\n') || 'No résumé or cover letter on file.';

    // Skip fields the standard-selector pass already handles via well-known
    // kinds — re-filling them with a sampled value would be wasted work and
    // could overwrite a clean value with model output. Match on the field's
    // name OR label so e.g. "First Name" and "firstName" both qualify.
    const STANDARD_FIELD_PATTERNS = /^(first[\s_-]?name|last[\s_-]?name|full[\s_-]?name|name|email|phone|mobile|tel|linkedin|website|portfolio|resume|cv|cover[\s_-]?letter)$/i;

    for (const formField of preview.formFields) {
      // Sample free-text inputs and textareas. Skip everything else (files,
      // checkboxes, radios are handled elsewhere; hidden was already filtered).
      const isFreeText = formField.type === 'textarea'
        || formField.type === 'text'
        || formField.type === 'url'
        || formField.type === 'tel'
        || formField.type === 'email';
      if (!isFreeText) continue;
      if (!formField.name || knownNames.has(formField.name)) continue;
      const labelOrName = (formField.label || formField.name).toLowerCase();
      if (/(?<![a-z])cover[\s_-]?letter/.test(labelOrName)) continue;
      // Skip if this looks like a field the standard-kind pass already fills.
      const normalizedName = formField.name.replace(/[\[\]]/g, ' ').trim();
      const normalizedLabel = (formField.label ?? '').trim();
      if (STANDARD_FIELD_PATTERNS.test(normalizedName) || STANDARD_FIELD_PATTERNS.test(normalizedLabel)) continue;

      // Answer bank first (deterministic), then fall back to the model.
      const banked = matchAnswer(ctx.db, formField.label || formField.name);
      const answer = banked ?? await sampleAnswerForFormField({
        sampling: ctx.sampling,
        formField,
        jobContext,
        applicantContext
      });
      if (answer && answer.length > 0) {
        fields.push({ kind: 'text_by_name', name: formField.name, value: answer, label: formField.label });
        sampledFields.push(formField.name);
      }
    }

    // Completion sweep: every preview field that has a visible label gets a
    // belt-and-braces label-keyed text_by_name entry, in case the original
    // name/id couldn't be resolved by selectors (label-based fallback inside
    // tryReactSelect picks it up). Covers cases where a custom EEO question
    // like "Please identify your race" has no addressable name/id.
    for (const formField of preview.formFields) {
      if (!formField.label) continue;
      const labelKey = formField.label.toLowerCase().replace(/[*?:]/g, '').trim();
      if (!labelKey) continue;
      const banked = matchAnswer(ctx.db, formField.label);
      if (!banked) continue;
      // Avoid duplicating answers already pushed under the field's name.
      const alreadyKeyed = fields.some(f =>
        ('name' in f) && f.value === banked
        && (f.name === formField.name || f.label === formField.label)
      );
      if (alreadyKeyed) continue;
      fields.push({ kind: 'text_by_name', name: formField.name || labelKey, value: banked, label: formField.label });
    }

    // Dropdowns / radios / checkboxes (answer bank → model fallback).
    const choiceFields = await resolveChoiceFields(ctx.db, ctx.sampling, preview.formFields, applicantContext);
    fields.push(...choiceFields);
  }

  const result = await ctx.browser.fillForm(
    app.deepLink,
    fields,
    {
      ...(detectedAts ? { ats: detectedAts } : {}),
      ...(input.submit ? { clickSubmit: true } : {}),
      maxSteps: getConfig(ctx.db).applyMaxSteps
    }
  );

  const submitted = Boolean(result.submitClicked);
  if (submitted) {
    addEventForApplication(ctx.db, app.id, 'browser_submitted', {
      postSubmitUrl: result.postSubmitUrl ?? null,
      postSubmitTitle: result.postSubmitTitle ?? null
    });
    try {
      updateApplicationStatus(ctx.db, app.id, 'submitted');
    } catch {
      // Already in submitted state or unknown — ignore
    }
  }

  return {
    applicationId: app.id,
    deepLink: app.deepLink,
    resolvedUrl: result.resolvedUrl,
    title: result.title,
    screenshotPngBase64: result.screenshotPng.toString('base64'),
    filled: result.filled,
    skipped: result.skipped,
    submitted,
    resumeDocxPath,
    coverLetterDocxPath,
    sampledFields,
    detectedAts,
    postSubmitUrl: result.postSubmitUrl
  };
}
