import { z } from 'zod';
import type { Db } from '../store/db.ts';
import { getApplication, addEventForApplication, updateApplicationStatus } from '../store/application.ts';
import { getProfile } from '../store/profile.ts';
import type { Browser, FillField } from '../services/browser/types.ts';
import { writeResumeDocxToTemp, writeCoverLetterDocxToTemp } from '../services/browser/resumeFile.ts';
import type { SamplingClient } from '../sampling/client.ts';
import { sampleAnswerForFormField } from '../services/sampling/answerFormField.ts';
import { getJob } from '../store/job.ts';
import { getCompany } from '../store/company.ts';
import { getConfig } from '../store/appConfig.ts';
import { matchAnswer } from '../store/answerBank.ts';
import { resolveChoiceFields } from '../services/resolveChoices.ts';
import { getEmailAccount } from '../store/email.ts';
import { enqueueNeedsAction } from '../store/notification.ts';
import { imapConfigFromAccount, liveImapFetcher } from '../services/email/imapReader.ts';
import { makeResolveVerification } from '../services/email/resolveVerification.ts';
import type { ResolveVerification } from '../services/browser/types.ts';
import { resolveApplyTarget } from '../services/applyUrl.ts';

export const applyApplicationInput = z.object({
  applicationId: z.string(),
  submit: z.boolean().optional()
});

export type ApplyApplicationResult = {
  applicationId: string;
  deepLink: string;
  resolvedUrl: string;
  title: string;
  /** PNG screenshot of the filled (but not submitted) form, base64-encoded. */
  screenshotPngBase64: string;
  /** Field kinds the browser successfully filled. */
  filled: string[];
  /** Field kinds the browser couldn't find a selector for. */
  skipped: string[];
  /** True if a submit button was clicked (v2.0+ opt-in via input.submit). False otherwise. */
  submitted: boolean;
  /** Path to the tailored resume DOCX written to /tmp. */
  resumeDocxPath: string;
  /** Path to the cover-letter DOCX. Undefined when the application has no cover letter. */
  coverLetterDocxPath?: string;
  /** Form-field names whose answers were generated by the LLM via sampling. */
  sampledFields: string[];
  /** ATS slug derived from the application's company. Null if the job/company isn't in the DB. */
  detectedAts: string | null;
  /** URL after submit click (post-navigation). Only set when submit succeeded. */
  postSubmitUrl?: string;
  /** True if the form demanded an emailed verification code/link. */
  verificationRequired?: boolean;
  /** True if that verification was resolved automatically. */
  verificationResolved?: boolean;
  /** Required fields the ATS flagged after a rejected submit (need an answer). */
  validationErrors?: string[];
};

function asString(v: unknown): string | undefined {
  return typeof v === 'string' && v.length > 0 ? v : undefined;
}

function safeHost(url: string): string {
  try { return new URL(url).host; } catch { return ''; }
}

/** Infer the ATS from a resolved apply URL so its field selectors apply.
 * Null when the host isn't a recognized ATS. */
function atsFromHost(host: string): import('../store/company.ts').KnownAts | null {
  if (/(^|\.)myworkdayjobs\.com$/.test(host)) return 'workday';
  if (/(^|\.)greenhouse\.io$/.test(host)) return 'greenhouse';
  if (/(^|\.)lever\.co$/.test(host)) return 'lever';
  if (/(^|\.)ashbyhq\.com$/.test(host)) return 'ashby';
  if (/(^|\.)workable\.com$/.test(host)) return 'workable';
  if (/(^|\.)smartrecruiters\.com$/.test(host)) return 'smartrecruiters';
  if (/(^|\.)bamboohr\.com$/.test(host)) return 'bamboohr';
  if (/(^|\.)recruitee\.com$/.test(host)) return 'recruitee';
  if (/(^|\.)icims\.com$/.test(host)) return 'icims';
  return null;
}

export async function applyApplication(
  input: z.infer<typeof applyApplicationInput>,
  ctx: { db: Db; browser: Browser; sampling: SamplingClient; fetchImpl?: typeof fetch }
): Promise<ApplyApplicationResult> {
  const app = getApplication(ctx.db, input.applicationId);
  if (!app) throw new Error(`unknown application: ${input.applicationId}`);

  const profile = getProfile(ctx.db) ?? {};
  const fields: FillField[] = [];

  const email = asString(profile.email);
  if (email) fields.push({ kind: 'email', value: email });

  const firstName = asString(profile.first_name);
  if (firstName) fields.push({ kind: 'first_name', value: firstName });

  const lastName = asString(profile.last_name);
  if (lastName) fields.push({ kind: 'last_name', value: lastName });

  // Always offer a full-name value: single-name forms (Ashby) need it even
  // when first/last exist. Forms without a full-name field just skip it.
  const fullName = asString(profile.name) ?? asString(profile.full_name)
    ?? ([firstName, lastName].filter(Boolean).join(' ') || undefined);
  if (fullName) {
    fields.push({ kind: 'full_name', value: fullName });
  }

  const phone = asString(profile.phone);
  if (phone) fields.push({ kind: 'phone', value: phone });

  const links = (profile.links ?? {}) as Record<string, unknown>;
  const linkedin = asString(profile.linkedin) ?? asString(links.linkedin);
  if (linkedin) fields.push({ kind: 'linkedin', value: linkedin });

  const website = asString(profile.website) ?? asString(links.website) ?? asString(links.portfolio);
  if (website) fields.push({ kind: 'website', value: website });

  const job = getJob(ctx.db, app.jobId);
  const company = job ? getCompany(ctx.db, job.companyId) : null;

  // Name the uploads Applicant_Company.docx — recruiters see this filename in
  // the ATS, so no internal IDs or tool branding.
  const docxNames = {
    ...(fullName ? { applicantName: fullName } : {}),
    ...(company?.name ? { companyName: company.name } : {})
  };
  const resumeDocxPath = await writeResumeDocxToTemp(app.tailoredResumeMd, app.id, docxNames);
  fields.push({ kind: 'resume_file', path: resumeDocxPath });

  let coverLetterDocxPath: string | undefined;
  if (app.coverLetterMd && app.coverLetterMd.length > 0) {
    coverLetterDocxPath = await writeCoverLetterDocxToTemp(app.coverLetterMd, app.id, docxNames);
    fields.push({ kind: 'cover_letter_file', path: coverLetterDocxPath });
    fields.push({ kind: 'cover_letter_text', value: app.coverLetterMd });
  }

  for (const [name, value] of Object.entries(app.answerPack)) {
    if (typeof value === 'string' && value.length > 0) {
      fields.push({ kind: 'text_by_name', name, value });
      // We don't have a label from the answer pack, but the apply pass will
      // also evaluate preview.formFields and may add a label-aware copy below.
    }
  }

  const sampledFields: string[] = [];
  const knownNames = new Set<string>();
  for (const f of fields) {
    if (f.kind === 'text_by_name') knownNames.add(f.name);
  }

  let detectedAts = company ? company.ats : null;

  // Aggregator listings (The Muse) carry no application form — resolve the
  // "Apply on company site" target and fill THAT, or refuse loudly. Filling
  // the listing page is how fake "submitted" statuses happen.
  let applyUrl = app.deepLink;
  if (detectedAts === 'themuse' || /(^|\.)themuse\.com$/.test(safeHost(app.deepLink))) {
    const target = await resolveApplyTarget(app.deepLink, ctx.fetchImpl);
    if (target.gone) {
      addEventForApplication(ctx.db, app.id, 'listing_expired', { url: app.deepLink });
      enqueueNeedsAction(ctx.db, {
        applicationId: app.id, reason: 'listing_expired',
        title: 'Listing expired',
        body: 'This listing is no longer accepting applications through this link.',
        link: app.deepLink
      });
      throw new Error('This listing has expired or been removed — the job is no longer accepting applications through this link.');
    }
    if (!target.url) {
      addEventForApplication(ctx.db, app.id, 'apply_url_unresolved', { url: app.deepLink });
      enqueueNeedsAction(ctx.db, {
        applicationId: app.id, reason: 'no_form',
        title: 'Apply on the company site',
        body: "Couldn't find the application form behind this listing — open it and apply manually.",
        link: app.deepLink
      });
      throw new Error(`This listing has no application form — apply on the company site: ${app.deepLink}`);
    }
    addEventForApplication(ctx.db, app.id, 'apply_url_resolved', { from: app.deepLink, to: target.url });
    applyUrl = target.url;
    // Use the resolved host's ATS so its field selectors apply (Workday's
    // data-automation-id inputs, Greenhouse names, …).
    detectedAts = atsFromHost(safeHost(target.url));
  }

  // Company-hosted Greenhouse pages (stripe.com/jobs, careers.airbnb.com)
  // bury the form in an iframe behind trackers; the identical form loads
  // standalone at the embed URL — apply there, like a hosted board.
  if (detectedAts === 'greenhouse' && !/(^|\.)greenhouse\.io$/.test(safeHost(applyUrl))) {
    const m = /^greenhouse:([^:]+):(\d+)$/.exec(app.jobId);
    if (m) {
      const embedUrl = `https://job-boards.greenhouse.io/embed/job_app?for=${m[1]}&token=${m[2]}`;
      addEventForApplication(ctx.db, app.id, 'apply_url_resolved', { from: applyUrl, to: embedUrl });
      applyUrl = embedUrl;
    }
  }

  let preview: Awaited<ReturnType<Browser['preview']>> | null = null;
  try {
    preview = await ctx.browser.preview(applyUrl);
  } catch {
    preview = null;
  }

  if (preview && preview.formFields.length > 0) {
    const jobContext = job
      ? `Applying to: ${job.title}${company ? ` at ${company.name}` : ''}`
      : 'a job application';
    // Bundle the profile (work authorization, location, links live HERE, not
    // in the résumé) + tailored résumé (real work history) + cover letter so
    // the sampler has the candidate's actual facts, not just motivational
    // prose. The model was confusing target company with current employer
    // when only the cover letter was given, and skipping factual dropdowns
    // (work auth) it could have answered from the profile.
    const profileText = Object.keys(profile).length > 0
      ? `--- Applicant's profile (true facts) ---\n${JSON.stringify(profile)}`
      : '';
    // 6000 chars, not 3000: education sits at the BOTTOM of the résumé and
    // was being cut off, so school/degree dropdowns had nothing to go on.
    const resumeText = app.tailoredResumeMd ? `--- Applicant's résumé (true facts) ---\n${app.tailoredResumeMd.slice(0, 6000)}` : '';
    const coverText = (app.coverLetterMd && app.coverLetterMd.length > 0)
      ? `--- Applicant's cover letter ---\n${app.coverLetterMd.slice(0, 1200)}`
      : '';
    const applicantContext = [profileText, resumeText, coverText].filter(Boolean).join('\n\n') || 'No résumé or cover letter on file.';

    // Skip fields the standard-selector pass already handles via well-known
    // kinds — re-filling them with a sampled value would be wasted work and
    // could overwrite a clean value with model output. Match on the field's
    // name OR label so e.g. "First Name" and "firstName" both qualify.
    const STANDARD_FIELD_PATTERNS = /^(first[\s_-]?name|last[\s_-]?name|full[\s_-]?name|name|email|phone|mobile|tel|linkedin|website|portfolio|resume|cv|cover[\s_-]?letter)$/i;

    for (const formField of preview.formFields) {
      // Sample free-text inputs and textareas. Skip everything else (files,
      // checkboxes, radios are handled elsewhere; hidden was already filtered).
      const isFreeText = formField.type === 'textarea'
        || formField.type === 'text'
        || formField.type === 'url'
        || formField.type === 'tel'
        || formField.type === 'email';
      if (!isFreeText) continue;
      // Comboboxes with harvested options are choice fields — the choice
      // resolver picks from the real option list; prose would miss.
      if (formField.type === 'text' && (formField.options?.length ?? 0) > 0) continue;
      if (!formField.name || knownNames.has(formField.name)) continue;
      const labelOrName = (formField.label || formField.name).toLowerCase();
      if (/(?<![a-z])cover[\s_-]?letter/.test(labelOrName)) continue;
      // Skip if this looks like a field the standard-kind pass already fills.
      const normalizedName = formField.name.replace(/[\[\]]/g, ' ').trim();
      const normalizedLabel = (formField.label ?? '').trim();
      if (STANDARD_FIELD_PATTERNS.test(normalizedName) || STANDARD_FIELD_PATTERNS.test(normalizedLabel)) continue;

      // Answer bank first (deterministic), then fall back to the model.
      const banked = matchAnswer(ctx.db, formField.label || formField.name);
      const answer = banked ?? await sampleAnswerForFormField({
        sampling: ctx.sampling,
        formField,
        jobContext,
        applicantContext
      });
      if (answer && answer.length > 0) {
        fields.push({ kind: 'text_by_name', name: formField.name, value: answer, label: formField.label });
        sampledFields.push(formField.name);
      }
    }

    // Completion sweep: every preview field that has a visible label gets a
    // belt-and-braces label-keyed text_by_name entry, in case the original
    // name/id couldn't be resolved by selectors (label-based fallback inside
    // tryReactSelect picks it up). Covers cases where a custom EEO question
    // like "Please identify your race" has no addressable name/id.
    for (const formField of preview.formFields) {
      if (!formField.label) continue;
      const labelKey = formField.label.toLowerCase().replace(/[*?:]/g, '').trim();
      if (!labelKey) continue;
      const banked = matchAnswer(ctx.db, formField.label);
      if (!banked) continue;
      // Avoid duplicating answers already pushed under the field's name.
      const alreadyKeyed = fields.some(f =>
        f.kind === 'text_by_name' && f.value === banked
        && (f.name === formField.name || f.label === formField.label)
      );
      if (alreadyKeyed) continue;
      fields.push({ kind: 'text_by_name', name: formField.name || labelKey, value: banked, label: formField.label });
    }

    // Dropdowns / radios / checkboxes (answer bank → model fallback).
    const choiceFields = await resolveChoiceFields(ctx.db, ctx.sampling, preview.formFields, applicantContext);
    fields.push(...choiceFields);
  }

  // Build a verification callback only when an inbox is configured with usable
  // IMAP credentials. Without it, fillForm behaves exactly as before.
  let resolveVerification: ResolveVerification | undefined;
  const acct = getEmailAccount(ctx.db);
  if (acct) {
    const imapCfg = imapConfigFromAccount(acct);
    if (imapCfg) {
      resolveVerification = makeResolveVerification({
        fetcher: liveImapFetcher,
        cfg: imapCfg,
        timeoutMs: getConfig(ctx.db).verificationTimeoutMs,
        // Each poll opens a fresh IMAP session; 5s polling trips Gmail's
        // connection throttling and every fetch silently fails. 20s is
        // 12 polls per 4-minute window — plenty, and under the radar.
        intervalMs: 20_000
      });
    }
  }

  const result = await ctx.browser.fillForm(
    applyUrl,
    fields,
    {
      ...(detectedAts ? { ats: detectedAts } : {}),
      ...(input.submit ? { clickSubmit: true } : {}),
      maxSteps: getConfig(ctx.db).applyMaxSteps,
      ...(resolveVerification ? { resolveVerification } : {})
    }
  );

  // Nothing filled at all usually means there was no reachable form — e.g. an
  // account-gated ATS (Workday sign-in wall). Don't leave the user guessing.
  if (result.filled.length === 0) {
    addEventForApplication(ctx.db, app.id, 'nothing_filled', { url: result.resolvedUrl });
    enqueueNeedsAction(ctx.db, {
      applicationId: app.id, reason: 'account_wall',
      title: 'Form needs you — likely a sign-in wall',
      body: 'No fields could be filled (often a Workday-style account wall). Finish it by hand.',
      link: result.resolvedUrl || applyUrl
    });
  }

  // A submit button gets clicked to TRIGGER the verification email (it advances
  // to the code/link screen), so submitClicked can be true while the gate is
  // still unresolved. That is not a real submission — don't mark it submitted.
  const verificationPending = Boolean(result.verificationRequired) && !result.verificationResolved;
  // A click alone is not a submission — require evidence: the page navigated
  // somewhere new, a confirmation page appeared, or a verification gate was
  // genuinely resolved. A false "submitted" is the worst failure mode here.
  const navigated = Boolean(result.postSubmitUrl) && result.postSubmitUrl !== result.resolvedUrl;
  const CONFIRMATION_RE = /thank|confirm|received|success|submitted|application complete/i;
  const confirmed = CONFIRMATION_RE.test(result.postSubmitTitle ?? '') || CONFIRMATION_RE.test(result.postSubmitUrl ?? '');
  const evidence = navigated || confirmed || Boolean(result.verificationResolved) || Boolean(result.confirmationSeen);
  const submitted = Boolean(result.submitClicked) && !verificationPending && evidence;
  if (input.submit && !result.submitClicked && result.submitClickErrors?.length) {
    // The button was found but every click attempt threw — log why.
    addEventForApplication(ctx.db, app.id, 'submit_click_failed', { errors: result.submitClickErrors });
  }
  if (Boolean(result.submitClicked) && !verificationPending && !evidence) {
    // The ATS told us exactly why the submit didn't land (a required field is
    // empty/invalid) — surface that, not a vague "unconfirmed". Far more
    // actionable: the user knows the one field to fill.
    if (result.validationErrors && result.validationErrors.length > 0) {
      addEventForApplication(ctx.db, app.id, 'required_field_missing', {
        url: result.resolvedUrl,
        fields: result.validationErrors
      });
      const list = result.validationErrors.join(', ');
      enqueueNeedsAction(ctx.db, {
        applicationId: app.id, reason: 'required_field_missing',
        title: 'One field needs your answer',
        body: `The application is filled, but ${list} ${result.validationErrors.length === 1 ? 'is a required field that needs' : 'are required fields that need'} an answer before it can submit. Finish it here.`,
        link: applyUrl
      });
    } else {
      addEventForApplication(ctx.db, app.id, 'submit_unconfirmed', {
        url: result.resolvedUrl,
        postSubmitUrl: result.postSubmitUrl ?? null,
        postSubmitTitle: result.postSubmitTitle ?? null
      });
      enqueueNeedsAction(ctx.db, {
        applicationId: app.id, reason: 'submit_unconfirmed',
        title: 'Submission not confirmed',
        body: 'A submit button was clicked but nothing confirmed the application went through — check it yourself.',
        link: applyUrl
      });
    }
  }
  if (submitted) {
    addEventForApplication(ctx.db, app.id, 'browser_submitted', {
      postSubmitUrl: result.postSubmitUrl ?? null,
      postSubmitTitle: result.postSubmitTitle ?? null
    });
    try {
      updateApplicationStatus(ctx.db, app.id, 'submitted');
    } catch {
      // Already in submitted state or unknown — ignore
    }
  }

  if (verificationPending) {
    addEventForApplication(ctx.db, app.id, 'verification_pending', { url: result.resolvedUrl });
    enqueueNeedsAction(ctx.db, {
      applicationId: app.id, reason: 'verification_timeout',
      title: 'Email verification needed',
      body: `${result.title || 'An application'} asked for an emailed code/link we couldn't read in time. The form is filled — finish it by hand.`,
      link: result.resolvedUrl || applyUrl
    });
  } else if (result.verificationResolved) {
    addEventForApplication(ctx.db, app.id, 'email_verified', { url: result.resolvedUrl });
  }

  return {
    applicationId: app.id,
    deepLink: app.deepLink,
    resolvedUrl: result.resolvedUrl,
    title: result.title,
    screenshotPngBase64: result.screenshotPng.toString('base64'),
    filled: result.filled,
    skipped: result.skipped,
    submitted,
    resumeDocxPath,
    coverLetterDocxPath,
    sampledFields,
    detectedAts,
    postSubmitUrl: result.postSubmitUrl,
    verificationRequired: result.verificationRequired,
    verificationResolved: result.verificationResolved,
    validationErrors: result.validationErrors
  };
}
